[book]
title = "Brevis zkCoprocessor"
authors = ["jie"]
language = "en"

[output.html]
theme = "theme"
additional-css = ["theme/custom.css"]
site-url = "/"
git-repository-url = "https://github.com/brevis-network/zkCoprocessor-docs"
